- name: "Configure cart for roboshop project"
  hosts: cart
  become: true

  tasks:
    - name: "Disable nodejs module"
      ansible.builtin.command: "dnf module disable nodejs -y"
    
    - name: "Enable the nodejs:20 module"
      ansible.builtin.command: "dnf module enable nodejs:20 -y"

    - name: "Install nodejs"
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: "Add application user roboshop"
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: true
        state: present
    
    - name: "Delete the existing application directory"
      ansible.builtin.file:
        path: /app
        state: absent

    - name: "create application directory"
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: "Delete the existing cart data"
      ansible.builtin.file:
        path: /tmp/cart.zip
        state: absent
    
    - name: "Download the cart code from url"
      ansible.builtin.get_url:
        url: "https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip"
        dest: /tmp/cart.zip
    
    - name: "Unzip the downloaded file"
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: true

    - name: "Install npm dependencies"
      community.general.npm:
        name: npm
        path: /app
        state: present
    
    - name: "copy the cart.service.j2 file from templates"
      ansible.builtin.template:
        src: templates/cart.service.j2
        dest: /etc/systemd/system/cart.service
  
    - name: "Daemon reload"
      ansible.builtin.systemd:
        daemon_reload: true

    - name: "Start cart service"
      ansible.builtin.service:
        name: cart
        state: restarted
        enabled: true