- name: "Configure catalogue for roboshop project"
  hosts: catalogue
  become: true

  tasks:
    - name: "Disable nodejs module"
      ansible.builtin.command: "dnf module disable nodejs -y"
    
    - name: "Enable the nodejs:20 module"
      ansible.builtin.command: "dnf module enable nodejs:20 -y"

    - name: "Install nodejs"
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: "Add application user roboshop"
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: true
        state: present
    
    - name: "Delete the existing application directory"
      ansible.builtin.file:
        path: /app
        state: absent

    - name: "create application directory"
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: "Delete the existing catalogue data"
      ansible.builtin.file:
        path: /tmp/catalogue.zip
        state: absent
    
    - name: "Download the catalogue code from url"
      ansible.builtin.get_url:
        url: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
        dest: /tmp/catalogue.zip
    
    - name: "Unzip the downloaded file"
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: true

    - name: "Install npm dependencies"
      community.general.npm:
        name: npm
        path: /app
        state: present
    
    - name: "copy the catalgoue.service.j2 file from templates"
      ansible.builtin.template:
        src: templates/catalogue.service.j2
        dest: /etc/systemd/system/catalogue.service
    
    - name: "Copy mongodb repo file"
      ansible.builtin.copy:
        src: files/mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: "Install mongodb client"
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present
    
    #Load the masterdata for catalogue service
    - name: "Load the masterdata for catalogue service"
      ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output
    
    - name: "print catalogue output"
      ansible.builtin.debug:
        var: catalogue_output.stdout
    
    - name: "Load the masterdata for catalogue service"
      ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js

    - name: "Daemon reload"
      ansible.builtin.systemd:
        daemon_reload: true

    - name: "Start catalogue service"
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: true