- name: "Configure user backend for roboshop project"
  hosts: user
  become: true

  tasks:
    - name: "Disable nodejs module"
      ansible.builtin.command: "dnf module disable nodejs -y"
    
    - name: "Enable the nodejs:20 module"
      ansible.builtin.command: "dnf module enable nodejs:20 -y"

    - name: "Install nodejs"
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: "Add application user roboshop"
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: true
        state: present
    
    - name: "Delete the existing application directory"
      ansible.builtin.file:
        path: /app
        state: absent
    
    - name: "create application directory"
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name:  "Delete the existing user data"
      ansible.builtin.file:
        path: /tmp/user.zip
        state: absent
    
    - name: "Download the user code from url"
      ansible.builtin.get_url:
        url: "https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip"
        dest: /tmp/user.zip
    
    - name: "Unzip the downloaded file"
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: true
    
    - name: "Install npm dependencies"
      community.general.npm:
        path: /app

    - name: "Copy user systemd service file"
      ansible.builtin.template:
        src: templates/user.service
        dest: /etc/systemd/system/user.service

    - name: "System Daemon reload"
      ansible.builtin.systemd:
        daemon_reload: true
    
    - name: "start user service"
      ansible.builtin.service:
        name: user
        state: restarted
        enabled: true